### 데이터 분석을 위한 수집 데이터의 컬럼 확인

In [18]:
import pandas as pd
import os

base_path = 'C:/Users/Jason/Downloads/output/essential_csv'
csv_files = os.listdir(base_path)

common_columns = ['개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자', '영업상태코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자', 
                  '전화번호', '소재지면적', '소재지우편번호', '지번주소', '도로명주소', '도로명우편번호', '사업장명', '최종수정일자', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)']

differ_dict = {}

for csv_f in csv_files:
    try:
        df = pd.read_csv(os.path.join(base_path, csv_f), encoding='euc-kr')
    except UnicodeDecodeError:
        try:
            df = pd.read_csv(os.path.join(base_path, csv_f), encoding='utf-8')
        except UnicodeDecodeError:
            df = pd.read_csv(os.path.join(base_path, csv_f), encoding='cp949')
    print(csv_f)
    print(df[common_columns].info())
    for i in list(df.columns):
        if i not in common_columns:
            if i not in differ_dict:
                differ_dict[i] = 1
            else:
                differ_dict[i] += 1
differ_dict

서울시_노원구_골프연습장업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  124 non-null    int64
 1   관리번호      124 non-null    object
 2   인허가일자     124 non-null    object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    124 non-null    int64
 5   영업상태명     124 non-null    object
 6   상세영업상태코드  124 non-null    int64
 7   상세영업상태명   124 non-null    object
 8   폐업일자      62 non-null     float64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      93 non-null     object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   105 non-null    object
 15  지번주소      124 non-null    object
 16  도로명주소     118 non-null    object
 17  도로명우편번호   40 non-null     float64
 18  사업장명      124 non-null    object
 19  최종수정일자    124 non-null    object
 20  데이터갱신구분   124 non-null    object
 21  데이터갱신일자   124 non-null    object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   123 non-null    float64
 24  좌표정보(Y)   123 non-null    float64
dtypes: float64(10), int64(3), object(12)
memory usage: 24.3+ KB
None
서울시_노원구_공연장_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  11 non-null     int64
 1   관리번호      11 non-null     object
 2   인허가일자     11 non-null     object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    11 non-null     int64
 5   영업상태명     11 non-null     object
 6   상세영업상태코드  11 non-null     int64
 7   상세영업상태명   11 non-null     object
 8   폐업일자      5 non-null      float64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      6 non-null      object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   7 non-null      object
 15  지번주소      11 non-null     object
 16  도로명주소     11 non-null     object
 17  도로명우편번호   5 non-null      object
 18  사업장명      11 non-null     object
 19  최종수정일자    11 non-null     object
 20  데이터갱신구분   11 non-null     object
 21  데이터갱신일자   11 non-null     object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   11 non-null     float64
 24  좌표정보(Y)   11 non-null     float64
dtypes: float64(9), int64(3), object(13)
memory usage: 2.3+ KB
None
서울시_노원구_관광식당_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  3 non-null      int64
 1   관리번호      3 non-null      object
 2   인허가일자     3 non-null      object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    3 non-null      int64
 5   영업상태명     3 non-null      object
 6   상세영업상태코드  3 non-null      int64
 7   상세영업상태명   3 non-null      object
 8   폐업일자      1 non-null      object
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      3 non-null      object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   3 non-null      object
 15  지번주소      3 non-null      object
 16  도로명주소     3 non-null      object
 17  도로명우편번호   0 non-null      float64
 18  사업장명      3 non-null      object
 19  최종수정일자    3 non-null      object
 20  데이터갱신구분   3 non-null      object
 21  데이터갱신일자   3 non-null      object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   3 non-null      float64
 24  좌표정보(Y)   3 non-null      float64
dtypes: float64(9), int64(3), object(13)
memory usage: 732.0+ bytes
None
서울시_노원구_노래연습장업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  506 non-null    int64
 1   관리번호      506 non-null    object
 2   인허가일자     506 non-null    object
 3   인허가취소일자   7 non-null      float64
 4   영업상태코드    506 non-null    int64
 5   영업상태명     506 non-null    object
 6   상세영업상태코드  506 non-null    int64
 7   상세영업상태명   506 non-null    object
 8   폐업일자      241 non-null    object
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      17 non-null     object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   98 non-null     float64
 15  지번주소      506 non-null    object
 16  도로명주소     491 non-null    object
 17  도로명우편번호   337 non-null    float64
 18  사업장명      506 non-null    object
 19  최종수정일자    506 non-null    object
 20  데이터갱신구분   506 non-null    object
 21  데이터갱신일자   506 non-null    object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   502 non-null    float64
 24  좌표정보(Y)   502 non-null    float64
dtypes: float64(10), int64(3), object(12)
memory usage: 99.0+ KB
None
서울시_노원구_단란주점영업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  234 non-null    int64
 1   관리번호      234 non-null    object
 2   인허가일자     234 non-null    object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    234 non-null    int64
 5   영업상태명     234 non-null    object
 6   상세영업상태코드  234 non-null    int64
 7   상세영업상태명   234 non-null    object
 8   폐업일자      197 non-null    float64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      228 non-null    object
 13  소재지면적     234 non-null    float64
 14  소재지우편번호   234 non-null    object
 15  지번주소      234 non-null    object
 16  도로명주소     58 non-null     object
 17  도로명우편번호   54 non-null     float64
 18  사업장명      234 non-null    object
 19  최종수정일자    234 non-null    object
 20  데이터갱신구분   234 non-null    object
 21  데이터갱신일자   234 non-null    object
 22  업태구분명     234 non-null    object
 23  좌표정보(X)   228 non-null    float64
 24  좌표정보(Y)   228 non-null    float64
dtypes: float64(9), int64(3), object(13)
memory usage: 45.8+ KB
None
서울시_노원구_당구장업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437 entries, 0 to 436
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  437 non-null    int64
 1   관리번호      437 non-null    object
 2   인허가일자     437 non-null    object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    437 non-null    int64
 5   영업상태명     437 non-null    object
 6   상세영업상태코드  437 non-null    int64
 7   상세영업상태명   437 non-null    object
 8   폐업일자      329 non-null    object
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      116 non-null    object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   379 non-null    object
 15  지번주소      437 non-null    object
 16  도로명주소     422 non-null    object
 17  도로명우편번호   105 non-null    float64
 18  사업장명      437 non-null    object
 19  최종수정일자    437 non-null    object
 20  데이터갱신구분   437 non-null    object
 21  데이터갱신일자   437 non-null    object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   429 non-null    float64
 24  좌표정보(Y)   429 non-null    float64
dtypes: float64(9), int64(3), object(13)
memory usage: 85.5+ KB
None
서울시_노원구_대규모점포_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  29 non-null     int64
 1   관리번호      29 non-null     int64
 2   인허가일자     29 non-null     object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    29 non-null     int64
 5   영업상태명     29 non-null     object
 6   상세영업상태코드  29 non-null     int64
 7   상세영업상태명   29 non-null     object
 8   폐업일자      2 non-null      float64
 9   휴업시작일자    1 non-null      float64
 10  휴업종료일자    1 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      27 non-null     object
 13  소재지면적     29 non-null     float64
 14  소재지우편번호   12 non-null     object
 15  지번주소      28 non-null     object
 16  도로명주소     21 non-null     object
 17  도로명우편번호   21 non-null     object
 18  사업장명      29 non-null     object
 19  최종수정일자    29 non-null     object
 20  데이터갱신구분   29 non-null     object
 21  데이터갱신일자   29 non-null     object
 22  업태구분명     29 non-null     object
 23  좌표정보(X)   28 non-null     float64
 24  좌표정보(Y)   28 non-null     float64
dtypes: float64(8), int64(4), object(13)
memory usage: 5.8+ KB
None
서울시_노원구_목욕장업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  114 non-null    int64
 1   관리번호      114 non-null    object
 2   인허가일자     114 non-null    object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    114 non-null    int64
 5   영업상태명     114 non-null    object
 6   상세영업상태코드  114 non-null    int64
 7   상세영업상태명   114 non-null    object
 8   폐업일자      93 non-null     float64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      113 non-null    object
 13  소재지면적     114 non-null    object
 14  소재지우편번호   114 non-null    object
 15  지번주소      114 non-null    object
 16  도로명주소     45 non-null     object
 17  도로명우편번호   45 non-null     float64
 18  사업장명      114 non-null    object
 19  최종수정일자    114 non-null    object
 20  데이터갱신구분   114 non-null    object
 21  데이터갱신일자   114 non-null    object
 22  업태구분명     114 non-null    object
 23  좌표정보(X)   103 non-null    float64
 24  좌표정보(Y)   103 non-null    float64
dtypes: float64(8), int64(3), object(14)
memory usage: 22.4+ KB
None
서울시_노원구_비디오물시청제공업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  1 non-null      int64
 1   관리번호      1 non-null      object
 2   인허가일자     1 non-null      object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    1 non-null      int64
 5   영업상태명     1 non-null      object
 6   상세영업상태코드  1 non-null      int64
 7   상세영업상태명   1 non-null      object
 8   폐업일자      0 non-null      float64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      0 non-null      float64
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   0 non-null      float64
 15  지번주소      1 non-null      object
 16  도로명주소     1 non-null      object
 17  도로명우편번호   1 non-null      int64
 18  사업장명      1 non-null      object
 19  최종수정일자    1 non-null      object
 20  데이터갱신구분   1 non-null      object
 21  데이터갱신일자   1 non-null      object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   1 non-null      float64
 24  좌표정보(Y)   1 non-null      float64
dtypes: float64(11), int64(4), object(10)
memory usage: 332.0+ bytes
None
서울시_노원구_수영장업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  11 non-null     int64
 1   관리번호      11 non-null     object
 2   인허가일자     11 non-null     object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    11 non-null     int64
 5   영업상태명     11 non-null     object
 6   상세영업상태코드  11 non-null     int64
 7   상세영업상태명   11 non-null     object
 8   폐업일자      5 non-null      float64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      9 non-null      object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   8 non-null      object
 15  지번주소      11 non-null     object
 16  도로명주소     10 non-null     object
 17  도로명우편번호   6 non-null      float64
 18  사업장명      11 non-null     object
 19  최종수정일자    11 non-null     object
 20  데이터갱신구분   11 non-null     object
 21  데이터갱신일자   11 non-null     object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   11 non-null     float64
 24  좌표정보(Y)   11 non-null     float64
dtypes: float64(10), int64(3), object(12)
memory usage: 2.3+ KB
None
서울시_노원구_숙박업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  50 non-null     int64
 1   관리번호      50 non-null     object
 2   인허가일자     50 non-null     object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    50 non-null     int64
 5   영업상태명     50 non-null     object
 6   상세영업상태코드  50 non-null     int64
 7   상세영업상태명   50 non-null     object
 8   폐업일자      22 non-null     object
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      48 non-null     object
 13  소재지면적     50 non-null     object
 14  소재지우편번호   50 non-null     object
 15  지번주소      50 non-null     object
 16  도로명주소     42 non-null     object
 17  도로명우편번호   39 non-null     float64
 18  사업장명      50 non-null     object
 19  최종수정일자    50 non-null     object
 20  데이터갱신구분   50 non-null     object
 21  데이터갱신일자   50 non-null     object
 22  업태구분명     50 non-null     object
 23  좌표정보(X)   49 non-null     float64
 24  좌표정보(Y)   49 non-null     float64
dtypes: float64(7), int64(3), object(15)
memory usage: 9.9+ KB
None
서울시_노원구_식품판매업(기타)_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  116 non-null    int64
 1   관리번호      116 non-null    object
 2   인허가일자     116 non-null    object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    116 non-null    int64
 5   영업상태명     116 non-null    object
 6   상세영업상태코드  116 non-null    int64
 7   상세영업상태명   116 non-null    object
 8   폐업일자      65 non-null     object
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      101 non-null    object
 13  소재지면적     114 non-null    object
 14  소재지우편번호   116 non-null    object
 15  지번주소      116 non-null    object
 16  도로명주소     75 non-null     object
 17  도로명우편번호   75 non-null     float64
 18  사업장명      116 non-null    object
 19  최종수정일자    116 non-null    object
 20  데이터갱신구분   116 non-null    object
 21  데이터갱신일자   116 non-null    object
 22  업태구분명     116 non-null    object
 23  좌표정보(X)   115 non-null    float64
 24  좌표정보(Y)   115 non-null    float64
dtypes: float64(7), int64(3), object(15)
memory usage: 22.8+ KB
None
서울시_노원구_영화상영관_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  32 non-null     int64
 1   관리번호      32 non-null     object
 2   인허가일자     32 non-null     object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    32 non-null     int64
 5   영업상태명     32 non-null     object
 6   상세영업상태코드  32 non-null     int64
 7   상세영업상태명   32 non-null     object
 8   폐업일자      4 non-null      float64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      25 non-null     object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   3 non-null      float64
 15  지번주소      32 non-null     object
 16  도로명주소     32 non-null     object
 17  도로명우편번호   14 non-null     float64
 18  사업장명      32 non-null     object
 19  최종수정일자    32 non-null     object
 20  데이터갱신구분   32 non-null     object
 21  데이터갱신일자   32 non-null     object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   32 non-null     float64
 24  좌표정보(Y)   32 non-null     float64
dtypes: float64(11), int64(3), object(11)
memory usage: 6.4+ KB
None
서울시_노원구_외국인관광도시민박업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  11 non-null     int64
 1   관리번호      11 non-null     object
 2   인허가일자     11 non-null     object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    11 non-null     int64
 5   영업상태명     11 non-null     object
 6   상세영업상태코드  11 non-null     int64
 7   상세영업상태명   11 non-null     object
 8   폐업일자      5 non-null      float64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      1 non-null      object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   4 non-null      object
 15  지번주소      11 non-null     object
 16  도로명주소     11 non-null     object
 17  도로명우편번호   6 non-null      float64
 18  사업장명      11 non-null     object
 19  최종수정일자    11 non-null     object
 20  데이터갱신구분   11 non-null     object
 21  데이터갱신일자   11 non-null     object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   11 non-null     float64
 24  좌표정보(Y)   11 non-null     float64
dtypes: float64(10), int64(3), object(12)
memory usage: 2.3+ KB
None
서울시_노원구_유원시설업(기타)_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  31 non-null     int64
 1   관리번호      31 non-null     object
 2   인허가일자     31 non-null     object
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    31 non-null     int64
 5   영업상태명     31 non-null     object
 6   상세영업상태코드  31 non-null     int64
 7   상세영업상태명   31 non-null     object
 8   폐업일자      15 non-null     object
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      11 non-null     object
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   5 non-null      float64
 15  지번주소      31 non-null     object
 16  도로명주소     31 non-null     object
 17  도로명우편번호   29 non-null     float64
 18  사업장명      31 non-null     object
 19  최종수정일자    31 non-null     object
 20  데이터갱신구분   31 non-null     object
 21  데이터갱신일자   31 non-null     object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   31 non-null     float64
 24  좌표정보(Y)   31 non-null     float64
dtypes: float64(10), int64(3), object(12)
memory usage: 6.2+ KB
None
서울시_노원구_일반야영장업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  1 non-null      int64
 1   관리번호      1 non-null      object
 2   인허가일자     1 non-null      int64
 3   인허가취소일자   0 non-null      float64
 4   영업상태코드    1 non-null      int64
 5   영업상태명     1 non-null      object
 6   상세영업상태코드  1 non-null      int64
 7   상세영업상태명   1 non-null      object
 8   폐업일자      1 non-null      int64
 9   휴업시작일자    0 non-null      float64
 10  휴업종료일자    0 non-null      float64
 11  재개업일자     0 non-null      float64
 12  전화번호      1 non-null      int64
 13  소재지면적     0 non-null      float64
 14  소재지우편번호   1 non-null      int64
 15  지번주소      1 non-null      object
 16  도로명주소     1 non-null      object
 17  도로명우편번호   1 non-null      int64
 18  사업장명      1 non-null      object
 19  최종수정일자    1 non-null      object
 20  데이터갱신구분   1 non-null      object
 21  데이터갱신일자   1 non-null      object
 22  업태구분명     0 non-null      float64
 23  좌표정보(X)   1 non-null      float64
 24  좌표정보(Y)   1 non-null      float64
dtypes: float64(8), int64(8), object(9)
memory usage: 332.0+ bytes
None
서울시_노원구_일반여행업_인허가_정보.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   개방자치단체코드  42 non-null     int64
 1   관리번호      42 non-null     object
 2   인허가일자     42 non-null     object

{'문화체육업종명': 12,
 '공사립구분명': 3,
 '보험가입여부코드': 3,
 '지도자수': 3,
 '건축물동수': 3,
 '건축물연면적': 3,
 '회원모집총인원': 3,
 '세부업종명': 3,
 '법인명': 3,
 '문화사업자구분명': 9,
 '지역구분명': 9,
 '총층수': 9,
 '주변환경명': 9,
 '제작취급품목내용': 9,
 '보험기관명': 6,
 '건물용도명': 9,
 '지상층수': 9,
 '지하층수': 9,
 '객실수': 6,
 '건축연면적': 6,
 '영문상호명': 6,
 '영문상호주소': 6,
 '선박총톤수': 6,
 '선박척수': 6,
 '선박제원': 6,
 '무대면적': 6,
 '좌석수': 8,
 '기념품종류': 6,
 '회의실별동시수용인원': 6,
 '시설면적': 9,
 '놀이기구수내역': 6,
 '놀이시설수': 6,
 '방송시설유무': 6,
 '발전시설유무': 6,
 '의무실유무': 6,
 '안내소유무': 6,
 '기획여행보험시작일자': 6,
 '기획여행보험종료일자': 6,
 '자본금': 6,
 '보험시작일자': 6,
 '보험종료일자': 6,
 '부대시설내역': 6,
 '시설규모': 6,
 '통로너비': 3,
 '조명시설조도': 3,
 '노래방실수': 3,
 '청소년실수': 3,
 '비상계단여부': 3,
 '비상구여부': 3,
 '자동환기여부': 3,
 '청소년실여부': 3,
 '특수조명여부': 3,
 '방음시설여부': 3,
 '비디오재생기명': 3,
 '조명시설유무': 3,
 '음향시설여부': 3,
 '편의시설여부': 3,
 '소방시설여부': 3,
 '총게임기수': 3,
 '기존게임업외업종명': 3,
 '제공게임물명': 3,
 '공연장형태구분명': 3,
 '품목명': 3,
 '최초등록시점': 3,
 '위생업태명': 6,
 '남성종사자수': 6,
 '여성종사자수': 6,
 '영업장주변구분명': 4,
 '등급구분명': 4,
 '급수시설구분명': 4,
 '총인원': 4,
 '본사종업원수': 4,
 '공장사무직종업원수': 4,
 '공장판매직종업원수': 4,
 '공장생산직종업원수': 4,
 '건물소유구분명': 6,
 '보증액': 4,
 '월세액': 4,
 '다중이용업소여부': 6,
 '시설총규모': 4,
 '전통업소지정번호': 4,
 '전통업소주된음식': 4,
 '홈페이지': 4,
 '점포구분명': 1,
 '건물지상층수': 2,
 '건물지하층수': 2,
 '사용시작지상층': 2,
 '사용끝지상층': 2,
 '사용시작지하층': 2,
 '사용끝지하층': 2,
 '한실수': 2,
 '양실수': 2,
 '욕실수': 2,
 '발한실여부': 2,
 '조건부허가신고사유': 2,
 '조건부허가시작일자': 2,
 '조건부허가종료일자': 2,
 '세탁기수': 2,
 '회수건조수': 2,
 '침대수': 2,
 '승려수': 1,
 '신도수': 1,
 '창립연대': 1,
 '유래연혁': 1,
 '지정취소': 1,
 '지정취소일자': 1,
 '지정취소사유': 1,
 '전통사찰명': 1}

### MongoDB에 데이터 저장

In [8]:
from pymongo import MongoClient
import pandas as pd
import os, datetime
import json

with open('C:/Users/Jason/OneDrive/Laptop/Dev/Map/test_credential/mongo_info.json') as file:
    data = json.load(file)

# MongoDB 서버 IP 주소
HOST = data['server_ip']
# MongoDB 포트 번호
PORT = data['server_port']
# 사용자 이름
USERNAME = data['user_id']
# 비밀번호
PASSWORD = data['user_pw']
# 데이터베이스 이름
DATABASE = 'admin'
# MongoDB 연결 문자열
uri = f"mongodb://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
# 데이터베이스 명
selected_db = 'place_info'
# 컬렉션 명
selected_collection = 'shop'
# MongoDB에 연결
client = MongoClient(uri)
# 데이터베이스와 컬렉션 선택
db = client[selected_db]
collection = db[selected_collection]

base_path = 'C:/Users/Jason/Downloads/output/essential_csv'
csv_files = os.listdir(base_path)

# CSV 파일 순회
for csv_f in csv_files:
    # CSV 파일을 읽어서 DataFrame으로 변환
    try:
        df = pd.read_csv(os.path.join(base_path, csv_f), encoding='euc-kr')
    except UnicodeDecodeError:
        try:
            df = pd.read_csv(os.path.join(base_path, csv_f), encoding='utf-8')
        except UnicodeDecodeError:
            df = pd.read_csv(os.path.join(base_path, csv_f), encoding='cp949')
            
    # 영업상태명이 폐업인 데이터는 제외
    df = df[df['영업상태명'] != '폐업']
    print(csv_f, len(df))
    
    # DataFrame이 비어있으면 다음 CSV 파일로 넘어감
    if len(df) == 0:
        continue
    
    #  DataFrame에 "insertdt" 컬럼 추가
    df['insertdt'] = datetime.datetime.now()
    
    
    # DataFrame을 딕셔너리 리스트로 변환
    data = df.to_dict(orient='records')

    # 데이터를 MongoDB에 삽입
    collection.insert_many(data)

서울시_노원구_골프연습장업_인허가_정보.csv 73
서울시_노원구_공연장_인허가_정보.csv 6
서울시_노원구_관광식당_인허가_정보.csv 2
서울시_노원구_노래연습장업_인허가_정보.csv 268
서울시_노원구_단란주점영업_인허가_정보.csv 37
서울시_노원구_당구장업_인허가_정보.csv 148
서울시_노원구_대규모점포_인허가_정보.csv 27
서울시_노원구_목욕장업_인허가_정보.csv 21
서울시_노원구_비디오물시청제공업_인허가_정보.csv 1
서울시_노원구_수영장업_인허가_정보.csv 7
서울시_노원구_숙박업_인허가_정보.csv 28
서울시_노원구_식품판매업(기타)_인허가_정보.csv 51
서울시_노원구_영화상영관_인허가_정보.csv 28
서울시_노원구_외국인관광도시민박업_인허가_정보.csv 6
서울시_노원구_유원시설업(기타)_인허가_정보.csv 16
서울시_노원구_일반야영장업_인허가_정보.csv 0
서울시_노원구_일반여행업_인허가_정보.csv 34
서울시_노원구_일반음식점_인허가_정보.csv 3711
서울시_노원구_전통사찰_인허가_정보.csv 3
서울시_노원구_제과점영업_인허가_정보.csv 155
서울시_노원구_종합체육시설업_인허가_정보.csv 0

### MongoDB에 저장된 데이터 집계 - 업태구분명

In [10]:
pipeline = [
    {"$group": {"_id": "$업태구분명", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}}
]

result = collection.aggregate(pipeline)

for doc in result:
    print(doc["_id"], doc["count"])

한식 1538
nan 592
기타 496
호프/통닭 470
분식 315
일식 198
제과점영업 155
경양식 146
중국식 139
통닭(치킨) 94
감성주점 62
식육(숯불구이) 55
기타식품판매업 51
단란주점 37
외국음식전문점(인도,태국등) 36
까페 35
패스트푸드 27
횟집 20
여관업 19
김밥(도시락) 15
정종/대포집/소주방 15
뷔페식 14
라이브카페 13
패밀리레스트랑 11
공동탕업 8
그 밖의 대규모점포 8
공동탕업+찜질시설서비스영업 8
구분없음 7
키즈카페 5
찜질시설서비스영업 4
냉면집 4
일반호텔 4
여인숙업 4
대형마트 3
백화점 3
복합쇼핑몰 3
쇼핑센터 2
복어취급 2
관광호텔 1
목욕장업 기타 1
탕류(보신용) 1
시장 1

### MongoDB에 저장된 데이터 집계 - 건물지상/하층수

In [26]:
pipeline = [
    {"$group": {"_id": "$건물지상층수", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}}
]

result = collection.aggregate(pipeline)

results_str = ""

for doc in result:
    if str(doc["_id"]) == "None" or str(doc["_id"]) == "nan":
        results_str += f'{doc["_id"]} : {doc["count"]}, '
    else:
        results_str += f'{str(doc["_id"]).split(".")[0]}층 : {(doc["count"])}, '
     
results_str = results_str[:-2]
print(results_str)

None : 4573, nan : 34, 0층 : 6, 8층 : 3, 6층 : 2, 2층 : 2, 5층 : 1, 1층 : 1

In [27]:
pipeline = [
    {"$group": {"_id": "$건물지하층수", "count": {"$sum": 1}}},
    {"$sort": {"count": -1}}
]

result = collection.aggregate(pipeline)

results_str = ""

for doc in result:
    if str(doc["_id"]) == "None" or str(doc["_id"]) == "nan":
        results_str += f'{doc["_id"]} : {doc["count"]}, '
    else:
        results_str += f'{str(doc["_id"]).split(".")[0]}층 : {(doc["count"])}, '
     
results_str = results_str[:-2]
print(results_str)

None : 4573, nan : 34, 1층 : 9, 0층 : 6